### ISSUE TITLE
New CI Based on Standard FHIR Validator

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#64]
Replace Vonk based profile and resource validation with FHIR Validator (IG publisher)

- [x] Create new Dockerfile for fhir validator and ig-publisher
- [x] Update CLI - remove all validation via Vonk code
- [x] Update CircleCI YAML 
- [x] Update README
